/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface definitions {
  Profile: { [key: string]: any };
  data_collection_logs: {
    /**
     * Note:
     * This is a Primary Key.<pk/>
     */
    id: number;
    inserted_at: string;
    updated_at: string;
    status: "STARTED" | "COMPLETED" | "ERRORED";
    error?: string;
  };
  movie: {
    /**
     * Note:
     * This is a Primary Key.<pk/>
     */
    id: number;
    inserted_at: string;
    updated_at: string;
    release_date: string;
    themoviedb_id: number;
    status?: string;
    overview?: string;
    runtime?: number;
    title: string;
    original_language?: string;
    spoken_languages?: string;
    imdb_id?: string;
    genres?: string;
    poster_path?: string;
    additional_videos?: string;
    additional_images?: string;
  };
  tv_episode: {
    /**
     * Note:
     * This is a Primary Key.<pk/>
     * This is a Foreign Key to `tv_season.tv_series_id`.<fk table='tv_season' column='tv_series_id'/>
     */
    tv_series_id: number;
    /**
     * Note:
     * This is a Primary Key.<pk/>
     * This is a Foreign Key to `tv_season.season_number`.<fk table='tv_season' column='season_number'/>
     */
    season_number: number;
    /**
     * Note:
     * This is a Primary Key.<pk/>
     */
    episode_number: number;
    inserted_at: string;
    updated_at: string;
    release_date: string;
    episode_order?: number;
    name?: string;
    original_name?: string;
    profile_path?: string;
    overview?: string;
    additional_images?: string;
    additional_videos?: string;
  };
  tv_season: {
    /**
     * Note:
     * This is a Primary Key.<pk/>
     * This is a Foreign Key to `tv_series.id`.<fk table='tv_series' column='id'/>
     */
    tv_series_id: number;
    /**
     * Note:
     * This is a Primary Key.<pk/>
     */
    season_number: number;
    inserted_at: string;
    updated_at: string;
    air_date: string;
    poster_path?: string;
    overview?: string;
    name?: string;
    spoken_languages?: string;
    additional_images?: string;
    additional_videos?: string;
  };
  tv_series: {
    /**
     * Note:
     * This is a Primary Key.<pk/>
     */
    id: number;
    inserted_at: string;
    updated_at: string;
    release_date: string;
    genres?: string;
    themoviedb_id: number;
    status?: string;
    title?: string;
    number_of_episodes?: number;
    number_of_seasons?: number;
    overview?: string;
    poster_path?: string;
    tagline?: string;
    series_type?: string;
    additional_images?: string;
    additional_videos?: string;
  };
}
